### ISSUE TITLE
SevenSegmentModule pic-asm firmware

### ISSUE THREAD

**Issue by Tabbod** [Johnlon/SevenSegmentModule#1]
I saw this module demoed on your YT page and thought it was a nice, simple idea. I did a mock-up of the circuit on breadboard and wrote an alternative driver in pic-asm, instead of C.

I could send you the source and .hex to try, if you're interested!

**Comment by Johnlon** [comment]
Hi,
Yes send the code for interest.
What's the advantage of using ASM over C?

**Comment by Johnlon** [comment]
Hi,
Yes send the code for interest.
What's the advantage of using ASM over C?

**Comment by Johnlon** [comment]
Hi,
Yes send the code for interest.
What's the advantage of using ASM over C?

**Comment by Tabbod** [comment]
Advantages are code size and speed, especially for 8-bit pic asm as the instruction set wasn't designed with a compiler in mind. And for simple tasks like multiplexing a display, it allows you to minimize the time spent switching one digit off and the other on.

Attached. Apart from the init code, everything runs inside the interrupt handler:
[16F18446_BMD_01_src.asm.txt](https://github.com/Johnlon/SevenSegmentModule/files/7511238/16F18446_BMD_01_src.asm.txt)
[16F18446_BMD_01.X.production.hex.txt](https://github.com/Johnlon/SevenSegmentModule/files/7511240/16F18446_BMD_01.X.production.hex.txt)

**Comment by Johnlon** [comment]
Hi thanks for the clarification

Given the compiled  c program fits in the memory easily and also manages to
run the refresh at khz if I recall correctly, and given the c is easier to
understand and maintain then I don't recognize those advantages you
mentioned for this specific use case.

However I would imagine that it's conceivable that by using assembler that
the program could run at a lower clock speed while retaining the same
refresh rate and this might have the advantage of less power consumption
and that might be a tangible benefit.

But I guess I'd need to see the power saving in practice and also I suspect
the LEDs might even burn more juice than the pic. So even then I'd probably
stick with c.

Does that make sense?

**Comment by Tabbod** [comment]
It certainly makes sense, and with most other microcontrollers there would be little reason to enter into an assembly solution.

And you are right, the difference in power consumption is negligible. I did test with and without sleep, the current draw difference doesn't even come to a milliamp.

But using a hardware timer in conjunction with sleep allows you to turn the clock speed right up, which benefits my next point.

The main goal here was tightening up the multiplexing routine to vastly reduce dead time when switching between the digits (increasing apparent brightness), as there are multiple ports involved in driving the segments.

**Comment by Johnlon** [comment]
Yeah the dead time was why I bumped up the clock speed.

**Comment by Johnlon** [comment]
Thanks for the info
